### ISSUE TITLE
Change initial fee parameter to be less error prone

### ISSUE THREAD

**Issue by ruttkowa** [nateshmbhat/cardano-nft-minter#1]
We had this discussion in the dev portal (see https://github.com/cardano-foundation/developer-portal/pull/283) and I'd suggest to implement it as some sort of best practice to set the fee for the first transaction file to be set to 300000 initially.

Cheers,
Alex

**Comment by nateshmbhat** [comment]
Thanks a lot for your input. Will change it.

I would love it if u could raise a PR with this small change so that u will also be shown as a contributor.

**Comment by nateshmbhat** [comment]
this is fixed now 👍🏻 @ruttkowa
